import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { getGlobalSettings } from '../../wplib/globalSettings';
import { getRevalidateOptions, handleInvalidDataResponse } from '../../wplib/util';
import GlobalConstants from '../../GlobalConstants';
import { convertWPLocaleToNextJSLocale } from '../../wplib/util';
import { getPublishedCaseStudyDataBySlug, getPreviewCaseStudyDataByDatabaseID } from '../../wplib/caseStudies';
import BasePageWrapper from '../../components/page-templates/BasePageWrapper/BasePageWrapper';
import CaseStudyTemplate from '../../components/page-templates/CaseStudyTemplate/CaseStudyTemplate';
import { transformToFooterStructure } from '../../components/template-parts/Footer/Footer.datamediator';
import { pageHeaderToGlobalAlert } from '../../data-mediators/PageHeaderToGlobalAlertMediator';
import { mainMenuToMenu } from '../../components/template-parts/Header/Header.datamediator';
import { getAllCaseStudiesStaticPaths } from '../../wplib/caseStudies';
import { globalSettingsAndPageFooterToPageCTAData } from '../../data-mediators/PageFooterAndSettingsToPageCTA';

// NOTE:: this method is called with data from getStaticProps for a specific route (as generated by getStaticPaths())
export default function Page({ slug, postTypeData, caseStudy, globalAlertData, pageCTAData, footerMenu, menu }) {
	const { title, seo, content } = caseStudy;

	console.log(
		`case-studies/[slug].Page() - rendering case study: ${GlobalConstants.FrontendRoutes.CaseStudies}/${slug}`
	);

	return (
		<BasePageWrapper title={title ?? ''} seoData={seo} translatedPages={menu?.translatedPages}>
			<CaseStudyTemplate
				postTypeData={postTypeData}
				pageCTAData={pageCTAData}
				caseStudy={caseStudy}
				globalAlertData={globalAlertData}
				headerMenuData={menu}
				footerMenu={footerMenu}
			/>
		</BasePageWrapper>
	);
}

export async function getStaticProps(context = {}) {
	// console.log('case-studies/[slug].getStaticProps() - context', context);

	const slug = [context?.params.slug];
	const isPreview = Boolean(context?.preview); // force to boolean
	var databaseID = isPreview ? context?.previewData?.id : null;
	var token = isPreview ? context?.previewData?.token : null;

	// get global data (ex: menus, etc.) that doesn't change per page
	const { globalSettings, menus } = await getGlobalSettings(isPreview, context.locale);
	const mediatedFooterMenu = transformToFooterStructure(menus, globalSettings, context.locale);

	// get details from WP
	let caseStudy,
		postTypeData,
		translated = null;

	try {
		if (isPreview) {
			({ caseStudy, postTypeData, translated } = await getPreviewCaseStudyDataByDatabaseID(
				databaseID,
				token,
				context.locale
			));
		} else {
			({ caseStudy, postTypeData, translated } = await getPublishedCaseStudyDataBySlug(slug, context.locale));
		}
	} catch (error) {
		console.log(`case-studies/[slug].getStaticProps() - error while fetching caseStudy`, error);
		return handleInvalidDataResponse(error);
	}

	const menu = mainMenuToMenu(menus, globalSettings, translated, context.locale);

	// determine our global alert settings based off global settings and page settings
	const globalAlertData = pageHeaderToGlobalAlert(globalSettings, caseStudy.caseStudyFields);
	const pageCTAData = globalSettingsAndPageFooterToPageCTAData(globalSettings, caseStudy.pageFooter);

	const revalidateOptions = getRevalidateOptions();
	return {
		props: {
			slug,
			caseStudy,
			postTypeData,
			globalAlertData,
			pageCTAData,
			footerMenu: mediatedFooterMenu,
			menu,
			...(await serverSideTranslations(context.locale, ['common'])),
		},
		...revalidateOptions,
	};
}

// NOTE:: getStaticPaths always runs server side (ref: https://nextjs.org/docs/basic-features/data-fetching/get-static-paths)
export async function getStaticPaths() {
	// if the flag is set, do a build only - no building of actual pages
	if (process.env.NO_PRERENDERED_PATHS_FALLBACK_ONLY === 'on') {
		console.info(
			`case-studies/[slug].getStaticPaths() - NO_PRERENDERED_PATHS_FALLBACK_ONLY is on, not pre-generating any paths`
		);
		return {
			paths: [],
			fallback: 'blocking',
		};
	}

	const caseStudies = await getAllCaseStudiesStaticPaths();
	const paths = caseStudies.map((caseStudiesPage) => {
		let pageLocale = convertWPLocaleToNextJSLocale(caseStudiesPage.wpml_current_locale);
		return {
			params: {
				slug: caseStudiesPage.slug,
			},
			locale: pageLocale,
		};
	});

	return {
		paths,
		fallback: false,
	};
}
