const MarketoConstants = {
	marketoFallbackScriptUrl: '//lps.tricentis.com', // basepath used by the marketo scripts
	marketoFallbackScriptId: '070-PYT-570', // not to be confused with the marketo form id.
	marketoFallbackScriptEmbedSrc: '//lps.tricentis.com/js/forms2/js/forms2.min.js', // location of the marketo script min file.
	fallbackInvalidDomainList: [
		'@abv.bg',
		'@aim.com',
		'@alice.it',
		'@aliceadsl.fr',
		'@aol.com',
		'@arcor.de',
		'@att.net',
		'@baddata.com',
		'@bellsouth.net',
		'@bigpond.com',
		'@bigpond.net.au',
		'@bluewin.ch',
		'@blueyonder.co.uk',
		'@bol.com.br',
		'@centurytel.net',
		'@charter.net',
		'@chello.nl',
		'@club-internet.fr',
		'@comcast.net',
		'@cox.net',
		'@earthlink.net',
		'@email.com',
		'@emeil.ir',
		'@eufh-mail.de',
		'@facebook.com',
		'@free.fr',
		'@freenet.de',
		'@frontiernet.net',
		'@gmail.*',
		'@gmx.com',
		'@googlemail.com',
		'@grr.la',
		'@hetnet.nl',
		'@home.nl',
		'@hotmail.com',
		'@icloud.com',
		'@ig.com.br',
		'@juno.com',
		'@kabelmail.de',
		'@laposte.net',
		'@libero.it',
		'@live.com',
		'@lpu.co.in',
		'@lums.edu.pk',
		'@mac.com',
		'@mail.com',
		'@mail.ru',
		'@mailinator.com',
		'@mailismagic.com',
		'@me.com',
		'@msn.com',
		'@naver.com',
		'@neuf.fr',
		'@ntlworld.com',
		'@nwytg.com',
		'@nwytg.net',
		'@optonline.net',
		'@optusnet.com.au',
		'@orange.fr',
		'@outlook.com',
		'@outlook.jp',
		'@planet.nl',
		'@qq.com',
		'@rambler.ru',
		'@rediffmail.com',
		'@rocketmail.com',
		'@sbcglobal.net',
		'@sfr.fr',
		'@sharklasers.com',
		'@shaw.ca',
		'@sky.com',
		'@skynet.be',
		'@Storiqax.top',
		'@sympatico.ca',
		'@t-online.de',
		'@telenet.be',
		'@terra.com.br',
		'@tin.it',
		'@tiscali.co.uk',
		'@tiscali.it',
		'@ukr.net',
		'@uol.com.br',
		'@verizon.net',
		'@virgilio.it',
		'@voila.fr',
		'@vpslists.com',
		'@wanadoo.fr',
		'@web.de',
		'@windstream.net',
		'@wp.pl',
		'@xyz.com',
		'@yahoo.*',
		'@yandex.com',
		'@yandex.ru',
		'@ymail.com',
		'@yopmail.com',
		'@zonnet.nl',
		'@qmetry.com',
		'@visualstudio.com',
		'@microfocus.com',
		'@getzephyr.com',
		'@smartbear.com',
		'@practitest.com',
		'@inflectra.com',
		'@gurock.com',
		'@xpand-addons.com',
		'@plutora.com',
		'@adaptavist.com',
		'@testlodge.com',
		'@testuff.com',
		'@telerik.com',
		'@catchsoftware.com',
		'@polarion.com',
		'@zoho',
		'@126',
		'@163',
		'@sina',
		'@valanides.com',
		'@bugfoo.com',
		'@daum.net',
		'@syinxun.com',
		'@armyspy.com',
		'@hanmail.net',
		'@nate.com',
		'@paxven.com',
		'@eurokool.com',
		'@teleworm.us',
		'@mailinator',
	],
	fallbackPrefillFields: {
		ALM_Tool__c: 'ALM_Tool__c',
		Academy_Updates__c: 'Academy_Updates__c',
		Active_Project__c: 'Active_Project__c',
		Best_Method_of_Contact__c: 'Best_Method_of_Contact__c',
		Best_Time_to_Contact__c: 'Best_Time_to_Contact__c',
		Company: 'company',
		Conversation_Track__c: 'Conversation_Track__c',
		Country: 'country',
		Customer_Communications__c: 'Customer_Communications__c',
		Email: 'email',
		FirstName: 'firstName',
		Insider_Newsletter__c: 'Insider_Newsletter__c',
		LastName: 'lastName',
		Lead_Qualification_Stage__c: 'Lead_Qualification_Stage__c',
		Live_Events__c: 'Live_Events__c',
		Partner_Updates__c: 'Partner_Updates__c',
		Phone: 'phone',
		PostalCode: 'postalCode',
		Product_Updates__c: 'Product_Updates__c',
		Reason_for_contacting__c: 'Reason_for_contacting__c',
		Research_Thought_Leadership__c: 'Research_Thought_Leadership__c',
		Role__c: 'Role__c',
		Salutation: 'salutation',
		Software_Challenges__c: 'Software_Challenges__c',
		TCM_Tool__c: 'TCM_Tool__c',
		Timeframe__c: 'Timeframe__c',
		Unsubscribed: 'unsubscribed',
		formCountTRI: 'formCountTRI',
		optionalPhoneNumber: 'optionalPhoneNumber',
		primaryAreaofInterestCompanion: 'primaryAreaofInterestCompanion',
	},
	mktoI18n: {
		contactMeButton: 'Contact Me',
		registerButton: 'Register',
		reasonForContacting: 'Please select a reason for contacting',
		qtestTrial: {
			emailLabel: 'Your Email Will Be Your User Name',
			domainLabel: 'Create your qTest Web Address',
			domainHelp: 'Your qTest account will be available via this URL',
			passwordLabel: 'Password',
			passwordConfirmLabel: 'Confirm Password',
			passwordHelp: 'Password must be 8 to 16 characters, include at least one number and 1 letter.',
			noticeLabel: 'Important Notice',
			noticeText:
				"By selecting your data center location, Tricentis will use reasonable efforts to store your test data within a physical jurisdiction that is acceptable under your country's laws. Please note that if you are location in a non-EU jurisdiction, your data will be stored in the United States. For more information, please review our %s",
			privacyPolicyUrl: '/privacy-policy/',
			privacyPolicyText: 'Privacy Policy',
			provisioningMessage:
				'Please do NOT close this window until processing is completed. Otherwise you will not receive your email with your qTest account info. Thanks for your patience.',
			submitButtonLabel: 'Start My Trial',
			emailExistsError: 'User %s already exists.',
			domainValidation: {
				noSubdomains: 'No subdomains or .com, .net, etc.',
				maxLength: 'Maximum length is %d characters',
				minLength: 'Minimum length is %d characters',
				urlTaken: 'That URL is already taken',
				urlInvalid: 'That URL is invalid',
				success: 'Good to go!',
			},
		},
		toscaTrial: {
			emailLabel: 'Your Email Will Be Your User Name',
			passwordLabel: 'Password',
			passwordHelp:
				'Password must be at least 8 characters, include at least one number, one uppercase and one lowercase letter.',
			passwordConfirmLabel: 'Confirm Password',
			loadingEmailCheck: 'Checking email validity...',
			verifyEmailRequired: 'Verify email required, please check your email.',
			emailIneligibleError:
				'Sorry, this account currently or recently had a trial and is ineligible for another one at this time.',
			provisioningMessage:
				'Please do NOT close this window until processing is completed. Otherwise you will not receive your email with your Tosca trial info. Thanks for your patience.',
			errorStartingTrial: 'An error occurred starting your trial. Please contact support.',
			errorSendingEmail: 'An error occurred sending you a verification email. Please contact support.',
		},
		validationErrors: {
			enterValidBusEmail: 'Please enter a valid, business email address.',
			validEmail: 'Great! Your email is valid!',
			unexpectedReload: 'An unexpected error occurred. Please reload the page and try again.',
			unexpected: 'An unexpected error occurred.',
			onlyAlphaNumeric: 'Only letters and numbers are allowed',
			minLength: 'Please use at least %d characters',
			maxLength: 'Please use a maximum of %d characters',
			includeAlphaNum: 'Please include at least one number and one letter',
			includeULAlphaNum: 'Please include at least one uppercase and one lowercase letter and one number',
			invalidChar: 'Only letters, numbers, and the following special characters are allowed: %s',
			excludeSpecialChar: 'No special characters allowed',
			greatPassRemember: "Great password — don't forget it!",
			requiredField: 'This field is required.',
			passwordMismatch: 'Passwords do not match',
		},
	},
	mktoFormEndpoints: {
		formApi: '/api/forms/',
		URLbasePath: process.env.NEXT_PUBLIC_BACKEND_SERVER,
		marketoBackendPath: '/wp-json/tricentis/v1/', // used by the tosca trial form to perform 4 different actions,
		serviceObjectsBasePath: process.env.SERVICE_OBJECTS_BASE_URL,
	},
};

export default MarketoConstants;
